/**
 * GratisBrockiBackend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @springdoc.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Message } from './message';
import { Picture } from './picture';


export interface Item { 
    id?: number;
    createdDate?: string;
    lastModifiedDate?: string;
    archivedDate?: string;
    title?: string;
    description?: string;
    zipCode?: number;
    category?: Item.CategoryEnum;
    condition?: Item.ConditionEnum;
    owner?: User;
    pictures?: Set<Picture>;
    messages?: Array<Message>;
}
export namespace Item {
    export type CategoryEnum = 'ChildrenItemCategory' | 'ClothingItemCategory' | 'GardenItemCategory' | 'HouseholdItemCategory' | 'SportItemCategory' | 'VehicleItemCategory' | 'OtherItemCategory';
    export const CategoryEnum = {
        ChildrenItemCategory: 'ChildrenItemCategory' as CategoryEnum,
        ClothingItemCategory: 'ClothingItemCategory' as CategoryEnum,
        GardenItemCategory: 'GardenItemCategory' as CategoryEnum,
        HouseholdItemCategory: 'HouseholdItemCategory' as CategoryEnum,
        SportItemCategory: 'SportItemCategory' as CategoryEnum,
        VehicleItemCategory: 'VehicleItemCategory' as CategoryEnum,
        OtherItemCategory: 'OtherItemCategory' as CategoryEnum
    };
    export type ConditionEnum = 'USED' | 'NEW' | 'DEFECTIVE';
    export const ConditionEnum = {
        Used: 'USED' as ConditionEnum,
        New: 'NEW' as ConditionEnum,
        Defective: 'DEFECTIVE' as ConditionEnum
    };
}


