/**
 * GratisBrockiBackend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @springdoc.version@
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {MessageDto} from './messageDto';
import {FileDto} from "./fileDto";

export interface ItemDto {
    id?: number;
    title?: string;
    description?: string;
    zipCode?: number;
    category?: ItemDto.CategoryEnum;
    condition?: ItemDto.ConditionEnum;
    userId?: number;
    pictures?: Array<FileDto>;
    messages?: Array<MessageDto>;
}
export namespace ItemDto {
  export type CategoryEnum = 'CHILDREN' | 'CLOTHING' | 'GARDEN' | 'HOUSEHOLD' | 'SPORT' | 'VEHICLE' | 'OTHER';
  export const CategoryEnum = {
    Children: 'CHILDREN' as CategoryEnum,
    Clothing: 'CLOTHING' as CategoryEnum,
    Garden: 'GARDEN' as CategoryEnum,
    Household: 'HOUSEHOLD' as CategoryEnum,
    Sport: 'SPORT' as CategoryEnum,
    Vehicle: 'VEHICLE' as CategoryEnum,
    Other: 'OTHER' as CategoryEnum
  };
    export type ConditionEnum = 'USED' | 'NEW' | 'DEFECTIVE';
    export const ConditionEnum = {
        Used: 'USED' as ConditionEnum,
        New: 'NEW' as ConditionEnum,
        Defective: 'DEFECTIVE' as ConditionEnum
    };
}


