/**
 * GratisBrockiBackend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @springdoc.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PictureDto } from './pictureDto';


export interface ItemCreationDto { 
    title?: string;
    description?: string;
    zipCode?: number;
    category?: ItemCreationDto.CategoryEnum;
    condition?: ItemCreationDto.ConditionEnum;
    userId?: number;
    pictures?: Set<PictureDto>;
}
export namespace ItemCreationDto {
    export type CategoryEnum = 'ChildrenItemCategory' | 'ClothingItemCategory' | 'GardenItemCategory' | 'HouseholdItemCategory' | 'SportItemCategory' | 'VehicleItemCategory' | 'OtherItemCategory';
    export const CategoryEnum = {
        ChildrenItemCategory: 'ChildrenItemCategory' as CategoryEnum,
        ClothingItemCategory: 'ClothingItemCategory' as CategoryEnum,
        GardenItemCategory: 'GardenItemCategory' as CategoryEnum,
        HouseholdItemCategory: 'HouseholdItemCategory' as CategoryEnum,
        SportItemCategory: 'SportItemCategory' as CategoryEnum,
        VehicleItemCategory: 'VehicleItemCategory' as CategoryEnum,
        OtherItemCategory: 'OtherItemCategory' as CategoryEnum
    };
    export type ConditionEnum = 'USED' | 'NEW' | 'DEFECTIVE';
    export const ConditionEnum = {
        Used: 'USED' as ConditionEnum,
        New: 'NEW' as ConditionEnum,
        Defective: 'DEFECTIVE' as ConditionEnum
    };
}


