/**
 * GratisBrockiBackend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @springdoc.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    id?: number;
    username?: string;
    email?: string;
    phoneNumber?: string;
    role?: UserDto.RoleEnum;
}
export namespace UserDto {
    export type RoleEnum = 'ADMIN' | 'MODERATOR' | 'USER';
    export const RoleEnum = {
        Admin: 'ADMIN' as RoleEnum,
        Moderator: 'MODERATOR' as RoleEnum,
        User: 'USER' as RoleEnum
    };
}


